apiVersion: 1

datasources:
  - name: ClickHouse-Analytics
    uid: clickhouse-analytics
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: stackoverflow
      username: ${CLICKHOUSE_MCP_READER_USER}
      tlsSkipVerify: true
    secureJsonData:
      password: ${CLICKHOUSE_MCP_READER_PASSWORD}
